Converted tabs to space
```
$ python3 eopkg-cli
Traceback (most recent call last):
  File "eopkg-cli", line 18, in <module>
    import pisi
  File "/home/zaryob/Development/Zaryob/eopkg/pisi/__init__.py", line 41, in <module>
    import pisi.api
  File "/home/zaryob/Development/Zaryob/eopkg/pisi/api.py", line 26, in <module>
    import pisi.db.packagedb
  File "/home/zaryob/Development/Zaryob/eopkg/pisi/db/packagedb.py", line 24, in <module>
    import pisi.metadata
  File "/home/zaryob/Development/Zaryob/eopkg/pisi/metadata.py", line 24, in <module>
    import pisi.specfile as specfile
  File "/home/zaryob/Development/Zaryob/eopkg/pisi/specfile.py", line 454
    ''' Check whether SupportsClang was used '''
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
```